connector:
    name: Enhanced Connector
    jobs:
        enhanced_csv_product_export:
            title: pim_enhanced_connector.export.product.title
            type:  export
            steps:
                export:
                    title: pim_enhanced_connector.export.product.title
                    services:
                        reader:    pim_enhanced_connector.reader.product
                        processor: pim_enhanced_connector.processor.product_to_flat_array
                        writer:    pim_base_connector.writer.file.csv_product
                    parameters:
                        batch_size: 10
            templates:
                edit: PimEnhancedConnectorBundle:JobProfile:edit.html.twig

        pimgento_csv_family_export:
            title: pim_enhanced_connector.export.pimgento.family.title
            type:  export
            steps:
                export:
                    title:     pim_enhanced_connector.export.pimgento.family.title
                    services:
                        reader:    pim_base_connector.reader.orm.family
                        processor: pim_enhanced_connector.processor.family_to_flat_array
                        writer:    pim_base_connector.writer.file.csv

        pimgento_csv_attribute_export:
            title: pim_enhanced_connector.export.pimgento.attribute.title
            type:  export
            steps:
                export:
                    title:     pim_enhanced_connector.export.pimgento.attribute.title
                    services:
                        reader:    pim_base_connector.reader.orm.attribute
                        processor: pim_enhanced_connector.processor.attribute_to_flat_array
                        writer:    pim_base_connector.writer.file.csv
