services:
    pim_enhanced_connector.doctrine.query.filter.date_time:
        class: '%pim_enhanced_connector.doctrine.query.filter.date_time.class%'
        arguments:
            - '@pim_catalog.validator.helper.attribute'
            - []
            - ['updated']
            - ['>= WITH TIME','=', '<', '>', 'BETWEEN', 'NOT BETWEEN', 'EMPTY']
        tags:
            - { name: 'pim_catalog.doctrine.query.filter', priority: 40 }

